config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  resources :words, only: [:index, :new, :show, :create, :edit, :update] do
    collection do
      get 'search', as: :search
    end
    resources :word_descriptions
  end

  resources :discussions do
    member do
      post 'create', to: "discussions#reply", as: :reply
      get 'edit/:reply_id', to: "discussions#edit_reply", as: :edit_reply
      patch 'update/:reply_id', to: "discussions#update_reply", as: :update_reply
    end
  end

  resources :users, only: [ :index, :show ]

  get '/dashboard', to: "dashboard#index", as: :dashboard
  post 'search', to: "dashboard#search", as: :search_for_words

  resources :translations, only: [:index, :new, :create, :show]

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/discussion.rb
class Discussion < ApplicationRecord

  has_many :replies, class_name: "Discussion", foreign_key: "parent_id"

  belongs_to :user

  scope :not_hidden, -> { where(hidden: false)}
  scope :topics, -> { where( parent_id: nil ).order( pinned: :desc).order(replied_at: :desc).order(updated_at: :desc).not_hidden.includes(:replies) }
  scope :from_thread, -> (parent_id) { where(parent_id: parent_id).not_hidden }

  def last_reply
    if replies.count == 0
      self
    else

      replies.last
    end
  end

  def pinned=(value)
    # if discussion thread is topic, it can be pinned up
    unless self[:parent_id]
      self[:pinned] = value
      true
    else
      false
    end
  end

  def self.create_thread(topic, user)
    create( title: topic, user: user, parent_id: nil, body: "" )
  end

  def thread?
    self[:parent_id] == nil
  end

  def self.create_reply(body, user, parent_id)
    reply = create( title: "", body: body, user: user, parent_id: parent_id )
    update_replied_at(parent_id)
    reply
  end

  def parent
    if parent_id
      Discussion.find(parent_id)
    else
      nil
    end
  end

  def self.update_replied_at(parent_id)
    if parent = Discussion.find(parent_id)
      parent.update_columns( replied_at: Time.now )
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @discussions = Discussion.topics
    if @discussions.length == 0
      render :empty_index
    else
      render :index
    end
  end


  def show
    @discussion = find_visible_discussion(params[:id])
    @reply = Discussion.new(parent_id: @discussion)
  end

  def new
    @discussion = Discussion.new( user: current_user )
  end

  def reply
    @discussion = find_visible_discussion(params[:id])
    if @reply = Discussion.create_reply(discussion_params[:body], current_user, @discussion.id)
      redirect_to @discussion
    else
      render 'show'
    end
  end

  def create
    if @discussion = Discussion.create_thread(discussion_params[:title], current_user)
      Discussion.create_reply(discussion_params[:body], current_user, @discussion.id)
      redirect_to @discussion
    else
      render 'new'
    end
  end

  def update_reply
    @discussion = find_visible_discussion(params[:id])
    if @discussion && @reply = find_visible_discussion(params[:reply_id], current_user)
      if @reply.update(body: discussion_params[:body])
        redirect_to @discussion
      else
        render 'edit_reply'
      end
    else
      render 'edit_reply'
    end
  end

  def edit_reply
    puts "  edit_reply() #{params.inspect}"
    @discussion = find_visible_discussion(params[:id])
    if @discussion && @reply = find_visible_discussion(params[:reply_id], current_user)
      render 'edit_reply'
    else
      redirect_to @discussion
    end
  end

  private

  def find_visible_discussion(id, user = nil)
    if user
      Discussion.where(hidden:false, user: user).find(id)
    else
      Discussion.where(hidden: false).find(id)
    end
  end
  def discussion_params
    params.require(:discussion).permit(:title, :body)
  end

end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def show_edit_link(reply, user)
    if reply.user == user
      link_to "Edit", edit_reply_discussion_path(reply.parent, reply)
    end
  end
end

app/views/discussions/_answer.html.haml
%li
  = discussion.body

app/views/discussions/_form.html.haml
= form_for(@discussion, html: { class: "discussion-form pure-form pure-form-aligned"} ) do |f|
  .pure-control-group
    = f.label :title
    = f.text_field :title, class: "title"
  .pure-control-group
    = f.label :body
    = f.text_area :body, class: "body"
  .pure-controls
    = f.submit
    or
    = link_to "Cancel", discussions_path

app/views/discussions/_message.html.haml
%tr.message-row
  %td.cell.icon-cell
    .icon
  %td
    .message-body
      - if message.title && message.title.length > 0
        .cell.message-title= message.title
      .topic-body= simple_format(message.body)
      .footer
        %span.timestamp
          = time_ago_in_words(message.last_reply.updated_at)
          = t('discussions.index.time_ago')
        = t('discussions.index.from_user')
        %span.author
          = message.last_reply.user.email

app/views/discussions/_message_body.html.haml
.message
  .body= message.body if message.body  && message.parent_id
  .bottom-footer
    .created_at= message.created_at.to_s(:short)
    .updated_at= message.updated_at.to_s(:short)

app/views/discussions/_reply_form.html.haml
%tr
  %td.cell.icon-cell
    .icon
  %td
    = form_for(@reply, url: reply_discussion_path(@discussion), html: { class: "pure-form pure-form-stacked reply-form"}) do |f|
      = f.text_area :body, class: "pure-input-1", rows: 6
      = f.submit "Reply", class: "pure-button"

app/views/discussions/_topic.html.haml
%tr
  %td.cell.icon-cell
    .icon
      %i.fa.fa-envelope-o
  %td.cell
    .topic-title= link_to(message.title, discussion_path(message)) if message.title
    .footer
      %span.timestamp
        = time_ago_in_words(message.last_reply.updated_at)
        = t('discussions.index.time_ago')
      = t('discussions.index.from_user')
      %span.author
        = message.last_reply.user.email
  %td.cell.replies
    .number= message.replies.count - 1
    .label
      = t('discussions.index.replies')

app/views/discussions/_update_reply.html.haml
= form_for(@reply, url: update_reply_discussion_path(@discussion, @reply)) do |f|
  = f.text_area :body
  = f.submit "Reply"

app/views/discussions/edit_reply.html.haml
.main-content
  = render 'update_reply'
  %p
    = link_to "Cancel", @discussion

app/views/discussions/empty_index.html.haml
.sub-menu
  = link_to "Create topic", new_discussion_path, class: "pure-button pure-button-primary"
.main-content
  .big-notification
    = t('discussions.empty_index.message')

app/views/discussions/index.html.haml
.sub-menu
  = link_to new_discussion_path, class: "pure-button pure-button-primary" do
    %i.fa.fa-pencil-square-o
    = t('discussions.index.new_topic')
.main-content
  %table.messages
    %tbody
      = render partial: "topic", collection: @discussions, as: :message

app/views/discussions/new.html.haml
.main-content
  %h1 New
  = render 'form'

app/views/discussions/show.html.haml
.sub-menu
  = link_to "Back", discussions_path, class: "pure-button pure-button-primary"
.main-content
  %table.messages
    %tbody
      = render partial: 'message', object: @discussion, as: :message
      = render partial: "message", collection: @discussion.replies, as: :message
  %table.new-reply
    %tbody
      %tr
        = render 'reply_form'