config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  resources :words, only: [:index, :new, :show, :create, :edit, :update] do
    collection do
      get 'search', as: :search
    end
    resources :word_descriptions
  end

  resources :discussions do
    member do
      post 'create', to: "discussions#reply", as: :reply
      get 'edit/:reply_id', to: "discussions#edit_reply", as: :edit_reply
      patch 'update/:reply_id', to: "discussions#update_reply", as: :update_reply
    end
  end

  resources :users, only: [ :index, :show ]

  get '/dashboard', to: "dashboard#index", as: :dashboard
  post 'search', to: "dashboard#search", as: :search_for_words

  resources :translations, only: [:index, :new, :create, :show]

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :original, class_name: "Word", foreign_key: "original_id"
  belongs_to :translation, class_name: "Word", foreign_key: "translation_id"
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"

  validates :creator, presence: true
  scope :most_recent, ->(limit = 15) { order(created_at: :desc).limit(limit) }


  def self.create_two_way_translation(params)
    original_id = params.fetch(:original_id)
    translation_id = params.fetch(:translation_id)
    creator_id = params.fetch(:creator_id)
    original = create!( creator_id: creator_id, original_id: original_id, translation_id: translation_id)
    translation = create!( creator_id: creator_id, translation_id: original_id, original_id: translation_id)
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @search_words_path = search_words_path
    @translation = Translation.new
  end

  def index
    @translations = Translation.most_recent.order(created_at: :desc)
  end

  def create
    if @translation = Translation.create_two_way_translation(translation_params)
      redirect_to translation_path(@translation)
    else
      render 'new'
    end
  end

  def show
    @translation = Translation.find(params[:id])
  end

  private

  def translation_params(creator_id = current_user.id)
    params.require(:translation).permit( :original_id, :translation_id ).merge( creator_id: creator_id)
  end

end

app/helpers/translations_helper.rb
module TranslationsHelper
  def dynamic_word_field(form, name, options = {})
    #TODO fix this
    content_tag :div, {class: "searchable_wrap", val: name } do
      text_field_tag("#{name}[body]", "", { class: "searchable" }) +
      select_tag("#{name}[language_id]", options_for_select(languages_for_select)) +
      select_tag("#{name}[word_class_id]", options_for_select(word_classes_for_select)) +
      hidden_field_tag("#{name}[create_new]", false) +
      hidden_field_tag("#{name}[word_id]", "")

    end
  end
end

app/views/translations/_form.html.haml
= form_for(@translation, html: { class:"pure-form pure-form-aligned translations"} ) do |f|
  .pure-control-group
    = label_tag :original_body, t('translations.form.original')
    = text_field_tag :original_body, "", class: "body searchable"
    = select_tag(:original_language_id, options_for_select(languages_for_select), class: "language_id")
    = f.hidden_field :original_id, class: "primary"
  .pure-control-group
    = label_tag :original_body, t('translations.form.translation')
    = text_field_tag :translation_body, "", class: "body searchable"
    = select_tag(:translation_language_id, options_for_select(languages_for_select), class: "language_id")
    = f.hidden_field :translation_id, class: "primary"
  .pure-controls
    = f.submit(t('translations.form.submit'), class: "pure-button pure-button-primary")
    or
    = link_to t('translations.form.cancel'), translations_path

app/views/translations/_translation.html.haml
%tr
  %td= translation.id
  %td= translation.created_at.to_s(:short)

  %td= link_to translation.original.body, word_path(translation.original.id)
  %td= "(#{Language.find(translation.original.language_id)})"
  %td &rarr;
  %td= link_to translation.translation.body, word_path(translation.translation.id)
  %td= "(#{Language.find(translation.translation.language_id)})"
  %td= translation.creator.email

app/views/translations/index.html.haml
%h1.content-subhead
  = t('translations.index.title')
%table.pure-table.translations
  %thead
    %tr
      %th #
      %th= t('translations.index.created_at')
      %th= t('translations.index.original')
      %th= t('translations.index.language')
      %th &nbsp;
      %th= t('translations.index.translation')
      %th= t('translations.index.language')
      %th= t('translations.index.created_by')
  %tbody
    = render @translations
%p
  = link_to t('translations.index.create_new_translation'), new_translation_path, class: "pure-button pure-button-primary"

app/views/translations/new.html.haml
%h1.content-subhead
  = t('translations.new.title')
= render 'form'

app/views/translations/show.html.haml
.pure-g
  .pure-u-1-3
    %h1.content-subhead
      = t('translations.show.translations_detail')
    %table.pure-table.pure-table-bordered
      %tbody
        %tr
          %td.cell-header #
          %td= @translation.id
        %tr
          %td.cell-header= t('translations.show.table.original')
          %td
            = link_to @translation.original.body, @translation.original
            = "(#{Language.find(@translation.original.language_id)})"
        %tr
          %td.cell-header= t('translations.show.table.translation')
          %td
            = link_to @translation.translation.body, @translation.translation
            = "(#{Language.find(@translation.translation.language_id)})"
        %tr
          %td.cell-header= t('translations.show.table.created_at')
          %td= @translation.created_at.to_s(:short)
        %tr
          %td.cell-header= t('translations.show.table.updated_at')
          %td= @translation.updated_at.to_s(:short)
        %tr
          %td.cell-header= t('translations.show.table.created_by')
          %td= @translation.creator.email
%p
  = link_to t('translations.show.back'), words_path, class: "pure-button pure-button-primary"