config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  resources :words, only: [:index, :new, :show, :create, :edit, :update] do
    collection do
      get 'search', as: :search
    end
    resources :word_descriptions
  end

  resources :discussions do
    member do
      post 'create', to: "discussions#reply", as: :reply
      get 'edit/:reply_id', to: "discussions#edit_reply", as: :edit_reply
      patch 'update/:reply_id', to: "discussions#update_reply", as: :update_reply
    end
  end

  resources :users, only: [ :index, :show ]

  get '/dashboard', to: "dashboard#index", as: :dashboard
  post 'search', to: "dashboard#search", as: :search_for_words

  resources :translations, only: [:index, :new, :create, :show]

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  validates :body, presence: true
  validates :keyword, presence: true
  validates :language_id, presence: true
  validates :creator, presence: true
  has_many :translations, foreign_key: "original_id"
  has_many :descriptions, class_name: "WordDescription", foreign_key: "word_id"
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"

  before_validation :set_accent

  scope :most_recent, ->(limit = 15) { order(created_at: :desc).limit(limit) }

  def self.search(arg)
    keyword = Language::Accent.strip(arg)
    Word.where("keyword LIKE ?", "#{keyword}%").limit(10)
  end

  def set_accent
    self[:keyword] = Language::Accent.strip(self[:body] || "")
  end

  def language
    Language.find( self[:language_id] )
  end

  def word_class
    Language::WordClass.find(self[:word_class_id])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!

  def index
    @words = Word.most_recent.order(created_at: :desc)
  end

  def new
    @word = Word.new
  end

  def show
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])
    if @word.update_attributes(word_params)
      flash[:success] = t('words.word_description.form.successfully_updated')
      redirect_to @word
    else
      render 'edit'
    end
  end

  def edit
    @word = Word.find(params[:id])
  end

  def create
    if (@word = Word.create!(word_params))
      redirect_to word_path(@word)
    else
      render 'new'
    end
  end

  def search
    results = Word.search(params[:keyword])
    items = results.map { |w| {"value" => w.body, "data" => { "id" => w.id, "language_id" => w.language_id, "word_class_id" => w.word_class_id }}}
    render json: { "suggestions": items }
  end

  private

  def word_params(creator_id = current_user.id)
    params.require(:word).permit(:body, :language_id, :word_class_id).merge( creator_id: creator_id)
  end
end

app/helpers/words_helper.rb
module WordsHelper
  def languages_for_select
    Language::LANGUAGES.map do |key, value|
      [ value, key ]
    end
  end

  def word_classes_for_select
    Language::WordClass::WORD_CLASS.map do |key, value|
      [ value, key ]
    end
  end
end

app/views/words/_form.html.haml
= form_for(@word, html: { class: "pure-form pure-form-aligned" }) do |f|
  .pure-control-group
    = f.label :body, t('words.new.form.body')
    = f.text_field :body
  .pure-control-group
    = f.label :language_id, t('words.new.form.language_id')
    = f.select :language_id, options_for_select(languages_for_select)
  .pure-control-group
    = f.label :word_class_id, t('words.new.form.word_class_id')
    = f.select :word_class_id, options_for_select(word_classes_for_select)
  .pure-controls
    = f.submit value: t('words.new.form.submit'), class: "pure-button pure-button-primary"
    or
    = link_to  t('words.new.form.cancel'), words_path

app/views/words/_translation.html.haml
%tr
  %td= translation.translation.id
  %td= translation.translation.body
  %td= Language::find(translation.translation.language_id)
  %td= Language::WordClass.find(translation.translation.word_class_id)

app/views/words/_word.html.haml
%tr
  %td= link_to word.id, word
  %td= link_to word.body, word
  %td= word.keyword
  %td= Language.find(word.language_id)
  %td= Language::WordClass.find(word.word_class_id)
  %td= word.creator.email
  %td= word.descriptions.count

app/views/words/_word_description.html.haml
%tr
  %td= word_description.id
  %td= Language::find(word_description.language_id)
  %td= word_description.body
  %td= word_description.creator.profile_name
  %td
    = link_to t('words.word_description.edit'), edit_word_word_description_path(@word, word_description)
    |
    = link_to t('words.word_description.delete'), [@word, word_description], method: :delete, data: { confirm: "#{t('words.word_description.confirm_delete')}" }

app/views/words/_word_detail.html.haml
%table.pure-table.pure-table-bordered
  %tbody
    %tr
      %td.cell-header #
      %td= @word.id
    %tr
      %td.cell-header= t('words.show.table.body')
      %td= @word.body
    %tr
      %td.cell-header= t('words.show.table.keyword')
      %td= @word.keyword
    %tr
      %td.cell-header= t('words.show.table.language')
      %td= Language.find(@word.language_id)
    %tr
      %td.cell-header= t('words.show.table.word_class')
      %td= Language::WordClass.find(@word.word_class_id)
    %tr
      %td.cell-header= t('words.show.table.created_at')
      %td= @word.created_at.to_s(:short)
    %tr
      %td.cell-header= t('words.show.table.updated_at')
      %td= @word.updated_at.to_s(:short)
    %tr
      %td.cell-header= t('words.show.table.created_by')
      %td= @word.creator.email

app/views/words/edit.html.haml
%h1.content-subhead
  = t('words.edit.title')
= render 'form'

app/views/words/index.html.haml
%h1.content-subhead
  = t('words.index.title')
%table.pure-table
  %thead
    %tr
      %th #
      %th= t('words.index.table.body')
      %th= t('words.index.table.keyword')
      %th= t('words.index.table.language')
      %th= t('words.index.table.word_class')
      %th= t('words.index.table.creator')
      %th= t('words.index.table.descriptions')
  %tbody
    = render @words
%p
  = link_to "#{t('words.index.create_new_word')} &rarr;".html_safe, new_word_path, class: "pure-button pure-button-primary"

app/views/words/new.html.haml
%h1.content-subhead
  = t('words.new.title')
= render 'form'

app/views/words/show.html.haml
.pure-g
  .pure-u-1-3
    %h1.content-subhead
      = t('words.show.word_detail')
    = render 'word_detail'
  .pure-u-2-3
    %h1.content-subhead
      = t('words.show.word_descriptions')
    %table.pure-table.pure-table-bordered
      %thead
        %tr
          %th #
          %th= t('words.show.table.word_descriptions.language')
          %th= t('words.show.table.word_descriptions.description')
          %th= t('words.show.table.word_descriptions.creator')
          %th= t('words.show.table.word_descriptions.action')
      %tbody
        = render partial: "word_description", collection: @word.descriptions, as: :word_description
    %p
      = link_to t('words.show.table.word_description.create_new'), new_word_word_description_path(@word), class: "pure-button pure-button-primary"
%p
  = link_to t('words.show.back'), words_path, class: "pure-button pure-button-primary"
  = link_to t('words.show.edit'), edit_word_path(@word), class: "pure-button pure-button-primary"